import type { Metadata } from "next";
import { Sarabun, Kanit, Prompt, Mitr, Chakra_Petch } from "next/font/google";
import "./globals.css";
import { ThemeProvider as NextThemesProvider } from "next-themes";
import ThemeDataProvider from "../context/themeDataProvider";
import NextAuthProviders from "@/context/next-auth-providers";

const kanit = Kanit({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin", "thai"],
  display: "swap",
});

const prompt = Prompt({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin", "thai"],
  display: "swap",
});

const mitr = Mitr({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin", "thai"],
  display: "swap",
});

const chakraPetch = Chakra_Petch({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin", "thai"],
  display: "swap",
});

const sarabun = Sarabun({
  weight: ["400", "500", "600", "700"], // ระบุความหนา
  subsets: ["latin", "thai"], // รองรับภาษาไทย
  display: "swap", // ปรับการโหลดฟอนต์
});

export const metadata: Metadata = {
  title: "Classroom Online",
  description: "Generated by create next app",
  icons: {
    icon: "/next.svg",
    apple: "/next.svg",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en" suppressHydrationWarning >
      <body
        className={`${chakraPetch.className}  antialiased`}
      >
        <NextAuthProviders>
          <NextThemesProvider
            attribute={"class"}
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <ThemeDataProvider>
              {children}
            </ThemeDataProvider>
          </NextThemesProvider>
        </NextAuthProviders>
      </body>
    </html>
  );
}
